// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TemplateCard from "../Components/TemplateCard.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function TemplatesView(props) {
  var goBack = props.goBack;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("header", {
                      children: JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("div", {
                                  children: JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsx("button", {
                                                children: "← Back",
                                                className: "text-gray-500 hover:text-gray-700 mr-4",
                                                onClick: (function (param) {
                                                    goBack();
                                                  })
                                              }),
                                          JsxRuntime.jsx("h1", {
                                                children: "OAuth Templates",
                                                className: "text-xl font-semibold text-gray-900"
                                              })
                                        ],
                                        className: "flex items-center"
                                      }),
                                  className: "flex justify-between items-center py-4"
                                }),
                            className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"
                          }),
                      className: "bg-white shadow-sm border-b"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx(TemplateCard.make, {
                                    name: "Google OAuth",
                                    description: "Google Cloud OAuth 2.0 configuration",
                                    icon: "🔍"
                                  }),
                              JsxRuntime.jsx(TemplateCard.make, {
                                    name: "GitHub OAuth",
                                    description: "GitHub OAuth Apps configuration",
                                    icon: "🐙"
                                  }),
                              JsxRuntime.jsx(TemplateCard.make, {
                                    name: "Ory Hydra",
                                    description: "Ory Hydra OAuth 2.0 server",
                                    icon: "🌊"
                                  }),
                              JsxRuntime.jsx(TemplateCard.make, {
                                    name: "Auth0",
                                    description: "Auth0 Universal Login",
                                    icon: "🔐"
                                  }),
                              JsxRuntime.jsx(TemplateCard.make, {
                                    name: "Microsoft Azure",
                                    description: "Azure Active Directory",
                                    icon: "🏢"
                                  }),
                              JsxRuntime.jsx(TemplateCard.make, {
                                    name: "Custom Provider",
                                    description: "Build your own OAuth configuration",
                                    icon: "⚙️"
                                  })
                            ],
                            className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
                          }),
                      className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"
                    })
              ],
              className: "min-h-screen bg-gray-50"
            });
}

var make = TemplatesView;

export {
  make ,
}
/* TemplateCard Not a pure module */
