// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TemplatesView from "./Views/TemplatesView.res.mjs";
import * as StudioDashboard from "./StudioDashboard.res.mjs";
import * as StudioSpecEditor from "./StudioSpecEditor.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return "Dashboard";
      });
  var setCurrentView = match[1];
  var goToDashboard = function () {
    setCurrentView(function (param) {
          return "Dashboard";
        });
  };
  var goToSpecEditor = function () {
    setCurrentView(function (param) {
          return "SpecEditor";
        });
  };
  var goToTemplates = function () {
    setCurrentView(function (param) {
          return "Templates";
        });
  };
  switch (match[0]) {
    case "Dashboard" :
        return JsxRuntime.jsx(StudioDashboard.make, {
                    goToSpecEditor: goToSpecEditor,
                    goToTemplates: goToTemplates
                  });
    case "SpecEditor" :
        return JsxRuntime.jsx(StudioSpecEditor.make, {
                    goBack: goToDashboard
                  });
    case "Templates" :
        return JsxRuntime.jsx(TemplatesView.make, {
                    goBack: goToDashboard
                  });
    
  }
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
