// Generated by ReScript, PLEASE EDIT WITH CARE


function convertToAuthSpec(spec) {
  return {
          name: spec.name,
          clientId: spec.clientId,
          clientSecret: spec.clientSecret,
          authorizeUrl: spec.authorizeUrl,
          tokenUrl: spec.tokenUrl,
          redirectUri: spec.redirectUri,
          scopes: spec.scopes
        };
}

function generateTypeScriptSDK(spec, outputDir) {
  var convertedSpec = convertToAuthSpec(spec);
  globalThis.AuthSDKGenerator.generateTypeScript(convertedSpec, outputDir);
}

function generatePythonSDK(spec, outputDir) {
  var convertedSpec = convertToAuthSpec(spec);
  globalThis.AuthSDKGenerator.generatePython(convertedSpec, outputDir);
}

export {
  convertToAuthSpec ,
  generateTypeScriptSDK ,
  generatePythonSDK ,
}
/* No side effect */
