// Generated by ReScript, PLEASE EDIT WITH CARE

import * as QuickActionCard from "./Components/QuickActionCard.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function StudioDashboard(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("header", {
                      children: JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx("h1", {
                                                  children: "Auth SDK Studio",
                                                  className: "text-2xl font-bold text-gray-900"
                                                }),
                                            JsxRuntime.jsx("span", {
                                                  children: "Beta",
                                                  className: "ml-2 px-2 py-1 text-xs bg-blue-100 text-blue-800 rounded-full"
                                                })
                                          ],
                                          className: "flex items-center"
                                        }),
                                    JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx("button", {
                                                  children: "Docs",
                                                  className: "text-gray-500 hover:text-gray-700"
                                                }),
                                            JsxRuntime.jsx("button", {
                                                  children: "GitHub",
                                                  className: "text-gray-500 hover:text-gray-700"
                                                })
                                          ],
                                          className: "flex items-center space-x-4"
                                        })
                                  ],
                                  className: "flex justify-between items-center py-4"
                                }),
                            className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"
                          }),
                      className: "bg-white shadow-sm border-b"
                    }),
                JsxRuntime.jsxs("main", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h2", {
                                      children: "Generate OAuth SDKs Visually",
                                      className: "text-3xl font-bold text-gray-900 mb-4"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Create type-safe authentication SDKs for TypeScript, Python, and more. Design OAuth flows, preview code, and download production-ready packages.",
                                      className: "text-lg text-gray-600 max-w-2xl mx-auto"
                                    })
                              ],
                              className: "text-center mb-12"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(QuickActionCard.make, {
                                      title: "Create New Spec",
                                      description: "Start from scratch or use a template",
                                      icon: "✨",
                                      primary: true,
                                      onClick: (function () {
                                          console.log("Navigate to spec editor");
                                        })
                                    }),
                                JsxRuntime.jsx(QuickActionCard.make, {
                                      title: "Browse Templates",
                                      description: "Google, GitHub, Auth0, Ory Hydra",
                                      icon: "📚",
                                      onClick: (function () {
                                          console.log("Navigate to templates");
                                        })
                                    }),
                                JsxRuntime.jsx(QuickActionCard.make, {
                                      title: "Import Existing",
                                      description: "Upload existing auth configuration",
                                      icon: "📤",
                                      onClick: (function () {
                                          console.log("Show import dialog");
                                        })
                                    })
                              ],
                              className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-12"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h3", {
                                      children: "Recent Projects",
                                      className: "text-lg font-medium text-gray-900 mb-4"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "No recent projects. Create your first OAuth spec to get started!",
                                      className: "text-gray-500 text-center py-8"
                                    })
                              ],
                              className: "bg-white rounded-lg shadow p-6"
                            })
                      ],
                      className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"
                    })
              ],
              className: "min-h-screen bg-gray-50"
            });
}

var make = StudioDashboard;

export {
  make ,
}
/* QuickActionCard Not a pure module */
