// Generated by ReScript, PLEASE EDIT WITH CARE


var emptySpec_scopes = [];

var emptySpec = {
  name: "",
  clientId: "",
  clientSecret: undefined,
  authorizeUrl: "",
  tokenUrl: "",
  redirectUri: "http://localhost:3000/callback",
  scopes: emptySpec_scopes
};

export {
  emptySpec ,
}
/* No side effect */
