// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function AuthSpecPreview(props) {
  var spec = props.spec;
  var url = spec.introspectUrl;
  var introspectUrlStr = url !== undefined ? "introspect_url = \"" + url + "\"\n" : "";
  var url$1 = spec.revokeUrl;
  var revokeUrlStr = url$1 !== undefined ? "revoke_url = \"" + url$1 + "\"\n" : "";
  var authFileContent = "name = \"" + spec.name + "\"\nclient_id = \"" + spec.clientId + "\"\nauthorize_url = \"" + spec.authorizeUrl + "\"\ntoken_url = \"" + spec.tokenUrl + "\"\n" + introspectUrlStr + revokeUrlStr + "redirect_uri = \"" + spec.redirectUri + "\"\nscopes = \"" + spec.scopes.join(",") + "\"\n\n# Generated by Auth SDK Studio";
  return JsxRuntime.jsx("pre", {
              children: authFileContent,
              className: "whitespace-pre-wrap text-gray-800"
            });
}

var make = AuthSpecPreview;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
