// Auth Spec Preview Component

open Types

@react.component
let make = (~spec: authSpec) => {
  let introspectUrlStr = switch spec.introspectUrl {
  | Some(url) => `introspect_url = "${url}"\n`
  | None => ""
  }
  let revokeUrlStr = switch spec.revokeUrl {
  | Some(url) => `revoke_url = "${url}"\n`
  | None => ""
  }

  let authFileContent = `name = "${spec.name}"
client_id = "${spec.clientId}"
authorize_url = "${spec.authorizeUrl}"
token_url = "${spec.tokenUrl}"
${introspectUrlStr}${revokeUrlStr}redirect_uri = "${spec.redirectUri}"
scopes = "${spec.scopes->Array.join(",")}"

# Generated by Auth SDK Studio`

  <pre className="whitespace-pre-wrap text-gray-800">
    {authFileContent->React.string}
  </pre>
}