// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function AuthSpecPreview(props) {
  var spec = props.spec;
  var authFileContent = "name = \"" + spec.name + "\"\nclient_id = \"" + spec.clientId + "\"\nauthorize_url = \"" + spec.authorizeUrl + "\"\ntoken_url = \"" + spec.tokenUrl + "\"\nredirect_uri = \"" + spec.redirectUri + "\"\nscopes = \"" + spec.scopes.join(",") + "\"\n\n# Generated by Auth SDK Studio";
  return JsxRuntime.jsx("pre", {
              children: authFileContent,
              className: "whitespace-pre-wrap text-gray-800"
            });
}

var make = AuthSpecPreview;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
