// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function FormField(props) {
  var __placeholder = props.placeholder;
  var onChange = props.onChange;
  var placeholder = __placeholder !== undefined ? __placeholder : "";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("label", {
                      children: props.label,
                      className: "block text-sm font-medium text-gray-700 mb-2"
                    }),
                JsxRuntime.jsx("input", {
                      className: "w-full border border-gray-300 rounded-md px-3 py-2",
                      placeholder: placeholder,
                      value: props.value,
                      onChange: (function (e) {
                          var value = e.target.value;
                          onChange(value);
                        })
                    })
              ]
            });
}

var make = FormField;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
