// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function QuickActionCard(props) {
  var onClick = props.onClick;
  var __primary = props.primary;
  var primary = __primary !== undefined ? __primary : false;
  var baseClasses = "p-6 rounded-lg border cursor-pointer transition-all duration-200 hover:shadow-md";
  var cardClasses = primary ? baseClasses + " bg-blue-50 border-blue-200 hover:bg-blue-100" : baseClasses + " bg-white border-gray-200 hover:bg-gray-50";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: props.icon,
                      className: "text-2xl mb-3"
                    }),
                JsxRuntime.jsx("h3", {
                      children: props.title,
                      className: "text-lg font-medium text-gray-900 mb-2"
                    }),
                JsxRuntime.jsx("p", {
                      children: props.description,
                      className: "text-gray-600 text-sm"
                    })
              ],
              className: cardClasses,
              onClick: (function (param) {
                  onClick();
                })
            });
}

var make = QuickActionCard;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
