// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function TemplateCard(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: props.icon,
                      className: "text-2xl mb-3"
                    }),
                JsxRuntime.jsx("h3", {
                      children: props.name,
                      className: "text-lg font-medium text-gray-900 mb-2"
                    }),
                JsxRuntime.jsx("p", {
                      children: props.description,
                      className: "text-gray-600 text-sm"
                    })
              ],
              className: "bg-white rounded-lg shadow p-6 cursor-pointer hover:shadow-md transition-shadow"
            });
}

var make = TemplateCard;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
